### ISSUE TITLE
BACI without sublocations

### ISSUE THREAD

**Issue by lucasmartinezramirez** [bmtglobal/epower#1]
When trying to run the assespower() function I get this error:
Error in names(sublocation.sample.estimates) <- levels(dat$sublocation.unique) : 
  'names' attribute [29] must be the same length as the vector [0]

I ran this package succesfully several times with designs including sublocations but I don't get to do this one.

In the design_specification sheet I left blank the sublocation name and typed 1 in the number of sublocations.

Thank you for any help!

**Comment by beckyfisher** [comment]
Apologies @lucasmartinezramirez for not getting to this earlier. Thanks for the bug report. I have made some edits which have hopefully resolved this issue and pushed up the changes to github. If you get a chance could you test on your data and confirm?

**Comment by lucasmartinezramirez** [comment]
Thank you for your answer. Unfortunately, after re-installing the epower package I got the very same error. I don't find how it could be a problem on my data input, but I'll have a second look later to verify. Kind regards

**Comment by beckyfisher** [comment]
Hi @ lucasmartinezramirez, if you still get the error can you send me your example? I probably can't do any further troubleshooting without being able to reproduce the issue on my end.

**Comment by lucasmartinezramirez** [comment]
[Log1.xlsx](https://github.com/bmtglobal/epower/files/4059007/Log1.xlsx)
I hope it is useful for you. Please, let me know if you find the reason of the problem.

**Comment by beckyfisher** [comment]
Hi @lucasmartinezramirez I just ran this example on my own machine and am unable to produce any errors.
