### ISSUE TITLE
BACI error when using assesPower()

### ISSUE THREAD

**Issue by isabelbrandao** [bmtglobal/epower#5]
Hi, 

I'm having this error when trying the assessPower (). 

> assessPower()
Error in response.mat[index.BC, ] <- matrix(rep(BCeta, length(index.BC)),  : 
  replacement has length zero

Any suggestions?

**Comment by beckyfisher** [comment]
Hi Isabel, could you please provide a self contained  reproducible example for me to use to investigate?

**Comment by isabelbrandao** [comment]
Hi Rebecca, 

epower is working now. My issue was a typo error. I had after, before instead of After, Before. What is the difference between the variable CORAL and Response? They have the same values in the pilot_data table. Also, it is not clear the variable nscored.

Thanks for quick response.

Isabel

**Comment by beckyfisher** [comment]
Great to here it is resolved 😊
