### ISSUE TITLE
PIT histogram

### ISSUE THREAD

**Issue by isabelbrandao** [bmtglobal/epower#7]
Is there a way to extract PIT values? I want to customize it.

Isabel

**Comment by beckyfisher** [comment]
After running fitData, the plot of the PIT histogram can be done directly in R with:

hist(scenarioParams$result$cpo$pit,xlab="PIT values",main="")

the scenarioParams is a list with a lot of stuff in it, but the $result element is the INLA fit to the pilot data that is being used to draw the PIT histogram. You can use that to do/extract anything else you might want from an inla fit.
