### ISSUE TITLE
Is it only supported by Windows ?

### ISSUE THREAD

**Issue by colineCJ** [bmtglobal/epower#8]
Hello,
I am wondering if that is possible to install and use the package in a Linux system. I am using
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

I have the following message :
> install.packages("/tmp/epower-master.zip", repos = NULL, type = "win.binary")
Installing package into ‘/home/coline/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
Error in install.packages : cannot install Windows binary packages on this platform

I suppose the 'type="win.binary"' is not right, yet I followed recommendation ("Open R and select
“Install package(s) from local zip files…” from the “Packages” drop down menu"), so I suppose the "win.binary" comes from something detected from the package itself, since R has been installed under a Linux distribution on my laptop.

I also tried remove the 'type' argument, or 'type="source"', and I get the following message:
> install.packages("/tmp/epower-master.zip", repos = NULL)
Installing package into ‘/home/coline/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
Error in rawToChar(block[seq_len(ns)]) : 
  caractère nul au milieu de la chaîne : 'PK\003\004\n\0\0\0\0\0\026\xbc\xd5P\0\0\0\0\0\0\0\0\0\0\0\0\016\0\t\0epower-master/UT\005\0\001\x8cP\xf0^PK\003\004\n\0\0\0\b\0\026\xbc\xd5P\x8ewq\xa1\030\0\0\0\034\0\0\0\033\0\t\0epower-master/.Rb'
Warning in install.packages :
  installation of package ‘/tmp/epower-master.zip’ had non-zero exit status
> install.packages("/tmp/epower-master.zip", repos = NULL, type = "win.binary")

Is there any way I can solve that ?
Thank you very much in advance.

**Comment by colineCJ** [comment]
I have scrolled other forums, and I tried that:
> devtools::install_github("bmtglobal/epower")

It seems like it worked, I am going to try the package now and see if it works. Thank you !

**Comment by beckyfisher** [comment]
Hi ColineCJ, thanks for posting. If you can confirm that worked for you that would be great. Otherwise I can investigate. We are keen to make sure it runs on most platforms.

**Comment by colineCJ** [comment]
Hi Becky, it did work well on the pilot data from the excel workfile. I have tried to run in on my data, but I have arrived to the conclusion that my BACI design would be much simpler and actually cannot be modelled by this (we will have just one before sampling, maybe 1 or 2 after samplings, and are trying to simplify as much as possible the spatial structure, with 1 field per farm and several replicates per farm, so that would be just one level of spatial grouping).

**Comment by beckyfisher** [comment]
Hi Coline, epower was really designed with beyond BACI style designs in mind - this is described in detail in the MEE paper. So you must have at least three sampling times (two before and one after is sufficient) and at least three higher level locations (ie more than just one control and one impact - this is usually at least two impact and one control, but I think theoretically the other way would work ok too). If the design doesn't have those minimal hierarchical levels then epower cannot be used at this time, sorry.

**Comment by colineCJ** [comment]
Thanks Becky ! This is very well explained in the paper, but I suspect in the marine realm they might try to stick as much as possible to that three sampling times (two before). I have seen (and we are designing) other types (you may call these incomplete) BACI designs with just one before sampling time. I do understand that it's less powerful, especially it does not allow to unambiguously estimate inter-year natural variation. Thank you !
